export const REPORT_STRINGS = {
  TITLE: "Generate Report Laporan",
  DESCRIPTION: "Rekapitulasi semua pengaduan dan tanggapan dari sistem.",
  BTN_CSV: "Cetak Data (CSV)",
  BTN_PDF: "Cetak Resmi (PDF)",
  PDF_TITLE: "LAPORAN REKAPITULASI PENGADUAN MASYARAKAT",
  PDF_SUBTITLE: "Sistem Layanan Aspirasi dan Pengaduan Online (El-Ngadu)",
  PDF_FOOTER: "Dicetak secara otomatis oleh sistem El-Ngadu pada ",
  PDF_SIGNATURE_TITLE: "Mengetahui,",
  PDF_SIGNATURE_ROLE: "Kepala Instansi",
  FILTER_STATUS_ALL: "Semua Status",
  FILTER_STATUS_DIAJUKAN: "Diajukan",
  FILTER_STATUS_DIPROSES: "Diproses",
  FILTER_STATUS_SELESAI: "Selesai",
  TABLE_COL_ID: "ID",
  TABLE_COL_JUDUL: "Judul",
  TABLE_COL_KATEGORI: "Kategori",
  TABLE_COL_LOKASI: "Lokasi",
  TABLE_COL_TGL: "Tgl Lapor",
  TABLE_COL_STATUS: "Status",
  TABLE_COL_PELAPOR: "Pelapor",
  EMPTY_TITLE: "Belum ada data laporan",
  EMPTY_DESC: "Data akan muncul setelah ada pengaduan yang sesuai filter.",
  SUCCESS_EXPORT: "Report berhasil diekspor!",
  ERROR_EXPORT: "Tidak ada data untuk diekspor.",
};
