export const PAGE_TITLES = {
  HOME: "El-Ngadu",
  LOGIN: "Masuk",
  REGISTER: "Daftar",
  FORGOT_PASSWORD: "Lupa Password",
  RESET_PASSWORD: "Reset Password",
  DASHBOARD: "Dashboard",
  CREATE_COMPLAINT: "Buat Pengaduan",
  COMPLAINT_HISTORY: "Riwayat Pengaduan",
  COMPLAINT_DETAIL: "Detail Pengaduan",
  MANAGE_COMPLAINTS: "Kelola Pengaduan",
  MANAGE_OFFICERS: "Kelola Petugas",
  MANAGE_CITIZENS: "Kelola Masyarakat",
  REPORTS: "Laporan",
  SEARCH: "Pencarian",
  PROFILE: "Profil",
  HELP: "Pusat Bantuan",
  SETTINGS: "Pengaturan",
  NOT_FOUND: "404 Not Found",
  AI_SUPPORT: "Asisten AI",
} as const;

export const ROUTE_TITLE_MAP: Record<string, string> = {
  "/": PAGE_TITLES.HOME,
  "/login": PAGE_TITLES.LOGIN,
  "/register": PAGE_TITLES.REGISTER,
  "/forgot-password": PAGE_TITLES.FORGOT_PASSWORD,
  "/reset-password": PAGE_TITLES.RESET_PASSWORD,
  "/dashboard": PAGE_TITLES.DASHBOARD,
  "/dashboard/create-complaint": PAGE_TITLES.CREATE_COMPLAINT,
  "/dashboard/history": PAGE_TITLES.COMPLAINT_HISTORY,
  "/dashboard/manage-complaints": PAGE_TITLES.MANAGE_COMPLAINTS,
  "/dashboard/manage-officers": PAGE_TITLES.MANAGE_OFFICERS,
  "/dashboard/manage-citizens": PAGE_TITLES.MANAGE_CITIZENS,
  "/dashboard/reports": PAGE_TITLES.REPORTS,
  "/dashboard/search": PAGE_TITLES.SEARCH,
  "/dashboard/profile": PAGE_TITLES.PROFILE,
  "/dashboard/help": PAGE_TITLES.HELP,
  "/dashboard/settings": PAGE_TITLES.SETTINGS,
};
